/* Generated by Yosys 0.27+22 (git sha1 53c0a6b78, gcc 12.2.0-3ubuntu1 -fPIC -Os) */

module alu(a, b, s0, s1, rp_zero, ans);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [15:0] _07_;
  wire _08_;
  wire _09_;
  wire [15:0] _10_;
  wire [15:0] _11_;
  wire [15:0] _12_;
  wire [15:0] _13_;
  input [15:0] a;
  wire [15:0] a;
  output [15:0] ans;
  wire [15:0] ans;
  input [15:0] b;
  wire [15:0] b;
  output rp_zero;
  wire rp_zero;
  input s0;
  wire s0;
  input s1;
  wire s1;
  assign _00_ = a == 16'h0000;
  assign _01_ = _00_ ? 1'h1 : 1'h0;
  assign _02_ = ~ s1;
  assign _03_ = ~ s0;
  assign _04_ = _02_ & _03_;
  assign _05_ = ~ s1;
  assign _06_ = _05_ & s0;
  assign _07_ = a + b;
  assign _08_ = ~ s0;
  assign _09_ = s1 & _08_;
  assign _10_ = a - b;
  assign _11_ = _09_ ? _10_ : 16'hzzzz;
  assign _12_ = _06_ ? _07_ : _11_;
  assign _13_ = _04_ ? a : _12_;
  assign rp_zero = _01_;
  assign ans = _13_;
endmodule

module bc(clock, reset, ir_data_out, rf_rp_zero, pc_clr, pc_ld, pc_inc, ir_ld, i_rd, leds, d_addr, d_rd, d_wr, rf_s1, rf_s0, rf_w_data, rf_w_addr, rf_rp_addr, rf_rq_addr, rf_w_wr, rf_rp_rd
, rf_rq_rd, alu_s0, alu_s1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [3:0] _04_;
  reg [3:0] _05_ = 4'h0;
  reg _06_;
  reg _07_;
  reg _08_;
  reg _09_;
  reg _10_;
  reg [7:0] _11_;
  reg _12_;
  reg _13_;
  reg _14_;
  reg _15_;
  reg [7:0] _16_;
  reg [3:0] _17_;
  reg [3:0] _18_;
  reg [3:0] _19_;
  reg _20_;
  reg _21_;
  reg _22_;
  reg _23_;
  reg _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire [7:0] _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire [7:0] _46_;
  wire [3:0] _47_;
  wire [3:0] _48_;
  wire [3:0] _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire [3:0] _64_;
  wire _65_;
  wire [3:0] _66_;
  wire _67_;
  wire _68_;
  wire [3:0] _69_;
  wire [3:0] _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  wire _74_;
  wire _75_;
  wire _76_;
  wire _77_;
  output alu_s0;
  wire alu_s0;
  output alu_s1;
  wire alu_s1;
  input clock;
  wire clock;
  wire [3:0] current_state;
  output [7:0] d_addr;
  wire [7:0] d_addr;
  output d_rd;
  wire d_rd;
  output d_wr;
  wire d_wr;
  output i_rd;
  wire i_rd;
  input [15:0] ir_data_out;
  wire [15:0] ir_data_out;
  output ir_ld;
  wire ir_ld;
  output [3:0] leds;
  wire [3:0] leds;
  wire [3:0] next_state;
  output pc_clr;
  wire pc_clr;
  output pc_inc;
  wire pc_inc;
  output pc_ld;
  wire pc_ld;
  input reset;
  wire reset;
  output [3:0] rf_rp_addr;
  wire [3:0] rf_rp_addr;
  output rf_rp_rd;
  wire rf_rp_rd;
  input rf_rp_zero;
  wire rf_rp_zero;
  output [3:0] rf_rq_addr;
  wire [3:0] rf_rq_addr;
  output rf_rq_rd;
  wire rf_rq_rd;
  output rf_s0;
  wire rf_s0;
  output rf_s1;
  wire rf_s1;
  output [3:0] rf_w_addr;
  wire [3:0] rf_w_addr;
  output [7:0] rf_w_data;
  wire [7:0] rf_w_data;
  output rf_w_wr;
  wire rf_w_wr;
  assign _25_ = next_state == 4'h0;
  assign _26_ = next_state == 4'h1;
  assign _27_ = next_state == 4'h2;
  assign _28_ = next_state == 4'h4;
  assign _29_ = next_state == 4'h5;
  assign _30_ = next_state == 4'h6;
  assign _31_ = next_state == 4'h7;
  assign _32_ = next_state == 4'h8;
  assign _33_ = next_state == 4'h9;
  assign _34_ = next_state == 4'ha;
  assign _35_ = next_state == 4'h3;
  function [0:0] \229 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \229  = b[0:0];
      11'b?????????1?:
        \229  = b[1:1];
      11'b????????1??:
        \229  = b[2:2];
      11'b???????1???:
        \229  = b[3:3];
      11'b??????1????:
        \229  = b[4:4];
      11'b?????1?????:
        \229  = b[5:5];
      11'b????1??????:
        \229  = b[6:6];
      11'b???1???????:
        \229  = b[7:7];
      11'b??1????????:
        \229  = b[8:8];
      11'b?1?????????:
        \229  = b[9:9];
      11'b1??????????:
        \229  = b[10:10];
      default:
        \229  = a;
    endcase
  endfunction
  assign _36_ = \229 (_06_, { _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, 2'h1 }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \232 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \232  = b[0:0];
      11'b?????????1?:
        \232  = b[1:1];
      11'b????????1??:
        \232  = b[2:2];
      11'b???????1???:
        \232  = b[3:3];
      11'b??????1????:
        \232  = b[4:4];
      11'b?????1?????:
        \232  = b[5:5];
      11'b????1??????:
        \232  = b[6:6];
      11'b???1???????:
        \232  = b[7:7];
      11'b??1????????:
        \232  = b[8:8];
      11'b?1?????????:
        \232  = b[9:9];
      11'b1??????????:
        \232  = b[10:10];
      default:
        \232  = a;
    endcase
  endfunction
  assign _37_ = \232 (_07_, { _07_, 1'h1, _07_, _07_, _07_, _07_, _07_, _07_, _07_, 1'h0, _07_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \238 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \238  = b[0:0];
      11'b?????????1?:
        \238  = b[1:1];
      11'b????????1??:
        \238  = b[2:2];
      11'b???????1???:
        \238  = b[3:3];
      11'b??????1????:
        \238  = b[4:4];
      11'b?????1?????:
        \238  = b[5:5];
      11'b????1??????:
        \238  = b[6:6];
      11'b???1???????:
        \238  = b[7:7];
      11'b??1????????:
        \238  = b[8:8];
      11'b?1?????????:
        \238  = b[9:9];
      11'b1??????????:
        \238  = b[10:10];
      default:
        \238  = a;
    endcase
  endfunction
  assign _38_ = \238 (_08_, { 1'h0, _08_, _08_, _08_, _08_, _08_, 3'h1, _08_, 1'h0 }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \243 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \243  = b[0:0];
      11'b?????????1?:
        \243  = b[1:1];
      11'b????????1??:
        \243  = b[2:2];
      11'b???????1???:
        \243  = b[3:3];
      11'b??????1????:
        \243  = b[4:4];
      11'b?????1?????:
        \243  = b[5:5];
      11'b????1??????:
        \243  = b[6:6];
      11'b???1???????:
        \243  = b[7:7];
      11'b??1????????:
        \243  = b[8:8];
      11'b?1?????????:
        \243  = b[9:9];
      11'b1??????????:
        \243  = b[10:10];
      default:
        \243  = a;
    endcase
  endfunction
  assign _39_ = \243 (_09_, { 1'h0, _09_, _09_, _09_, _09_, _09_, 2'h0, _09_, 1'h1, _09_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \247 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \247  = b[0:0];
      11'b?????????1?:
        \247  = b[1:1];
      11'b????????1??:
        \247  = b[2:2];
      11'b???????1???:
        \247  = b[3:3];
      11'b??????1????:
        \247  = b[4:4];
      11'b?????1?????:
        \247  = b[5:5];
      11'b????1??????:
        \247  = b[6:6];
      11'b???1???????:
        \247  = b[7:7];
      11'b??1????????:
        \247  = b[8:8];
      11'b?1?????????:
        \247  = b[9:9];
      11'b1??????????:
        \247  = b[10:10];
      default:
        \247  = a;
    endcase
  endfunction
  assign _40_ = \247 (_10_, { _10_, _10_, _10_, _10_, _10_, _10_, 2'h0, _10_, 1'h1, _10_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [7:0] \248 ;
    input [7:0] a;
    input [87:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \248  = b[7:0];
      11'b?????????1?:
        \248  = b[15:8];
      11'b????????1??:
        \248  = b[23:16];
      11'b???????1???:
        \248  = b[31:24];
      11'b??????1????:
        \248  = b[39:32];
      11'b?????1?????:
        \248  = b[47:40];
      11'b????1??????:
        \248  = b[55:48];
      11'b???1???????:
        \248  = b[63:56];
      11'b??1????????:
        \248  = b[71:64];
      11'b?1?????????:
        \248  = b[79:72];
      11'b1??????????:
        \248  = b[87:80];
      default:
        \248  = a;
    endcase
  endfunction
  assign _41_ = \248 (_11_, { _11_, _11_, _11_, _11_, _11_, _11_, ir_data_out[7:0], ir_data_out[7:0], _11_, _11_, _11_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \251 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \251  = b[0:0];
      11'b?????????1?:
        \251  = b[1:1];
      11'b????????1??:
        \251  = b[2:2];
      11'b???????1???:
        \251  = b[3:3];
      11'b??????1????:
        \251  = b[4:4];
      11'b?????1?????:
        \251  = b[5:5];
      11'b????1??????:
        \251  = b[6:6];
      11'b???1???????:
        \251  = b[7:7];
      11'b??1????????:
        \251  = b[8:8];
      11'b?1?????????:
        \251  = b[9:9];
      11'b1??????????:
        \251  = b[10:10];
      default:
        \251  = a;
    endcase
  endfunction
  assign _42_ = \251 (_12_, { _12_, _12_, _12_, _12_, _12_, _12_, _12_, 1'h1, _12_, 1'h0, _12_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \254 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \254  = b[0:0];
      11'b?????????1?:
        \254  = b[1:1];
      11'b????????1??:
        \254  = b[2:2];
      11'b???????1???:
        \254  = b[3:3];
      11'b??????1????:
        \254  = b[4:4];
      11'b?????1?????:
        \254  = b[5:5];
      11'b????1??????:
        \254  = b[6:6];
      11'b???1???????:
        \254  = b[7:7];
      11'b??1????????:
        \254  = b[8:8];
      11'b?1?????????:
        \254  = b[9:9];
      11'b1??????????:
        \254  = b[10:10];
      default:
        \254  = a;
    endcase
  endfunction
  assign _43_ = \254 (_13_, { _13_, _13_, _13_, _13_, _13_, _13_, 1'h1, _13_, _13_, 1'h0, _13_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \259 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \259  = b[0:0];
      11'b?????????1?:
        \259  = b[1:1];
      11'b????????1??:
        \259  = b[2:2];
      11'b???????1???:
        \259  = b[3:3];
      11'b??????1????:
        \259  = b[4:4];
      11'b?????1?????:
        \259  = b[5:5];
      11'b????1??????:
        \259  = b[6:6];
      11'b???1???????:
        \259  = b[7:7];
      11'b??1????????:
        \259  = b[8:8];
      11'b?1?????????:
        \259  = b[9:9];
      11'b1??????????:
        \259  = b[10:10];
      default:
        \259  = a;
    endcase
  endfunction
  assign _44_ = \259 (_14_, { _14_, _14_, _14_, 3'h2, _14_, 1'h0, _14_, _14_, _14_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \264 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \264  = b[0:0];
      11'b?????????1?:
        \264  = b[1:1];
      11'b????????1??:
        \264  = b[2:2];
      11'b???????1???:
        \264  = b[3:3];
      11'b??????1????:
        \264  = b[4:4];
      11'b?????1?????:
        \264  = b[5:5];
      11'b????1??????:
        \264  = b[6:6];
      11'b???1???????:
        \264  = b[7:7];
      11'b??1????????:
        \264  = b[8:8];
      11'b?1?????????:
        \264  = b[9:9];
      11'b1??????????:
        \264  = b[10:10];
      default:
        \264  = a;
    endcase
  endfunction
  assign _45_ = \264 (_15_, { _15_, _15_, _15_, 3'h0, _15_, 1'h1, _15_, _15_, _15_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [7:0] \265 ;
    input [7:0] a;
    input [87:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \265  = b[7:0];
      11'b?????????1?:
        \265  = b[15:8];
      11'b????????1??:
        \265  = b[23:16];
      11'b???????1???:
        \265  = b[31:24];
      11'b??????1????:
        \265  = b[39:32];
      11'b?????1?????:
        \265  = b[47:40];
      11'b????1??????:
        \265  = b[55:48];
      11'b???1???????:
        \265  = b[63:56];
      11'b??1????????:
        \265  = b[71:64];
      11'b?1?????????:
        \265  = b[79:72];
      11'b1??????????:
        \265  = b[87:80];
      default:
        \265  = a;
    endcase
  endfunction
  assign _46_ = \265 (_16_, { _16_, _16_, _16_, _16_, ir_data_out[7:0], _16_, _16_, _16_, _16_, _16_, _16_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [3:0] \266 ;
    input [3:0] a;
    input [43:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \266  = b[3:0];
      11'b?????????1?:
        \266  = b[7:4];
      11'b????????1??:
        \266  = b[11:8];
      11'b???????1???:
        \266  = b[15:12];
      11'b??????1????:
        \266  = b[19:16];
      11'b?????1?????:
        \266  = b[23:20];
      11'b????1??????:
        \266  = b[27:24];
      11'b???1???????:
        \266  = b[31:28];
      11'b??1????????:
        \266  = b[35:32];
      11'b?1?????????:
        \266  = b[39:36];
      11'b1??????????:
        \266  = b[43:40];
      default:
        \266  = a;
    endcase
  endfunction
  assign _47_ = \266 (_17_, { _17_, _17_, _17_, ir_data_out[3:0], ir_data_out[11:8], ir_data_out[3:0], _17_, ir_data_out[11:8], _17_, _17_, _17_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [3:0] \267 ;
    input [3:0] a;
    input [43:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \267  = b[3:0];
      11'b?????????1?:
        \267  = b[7:4];
      11'b????????1??:
        \267  = b[11:8];
      11'b???????1???:
        \267  = b[15:12];
      11'b??????1????:
        \267  = b[19:16];
      11'b?????1?????:
        \267  = b[23:20];
      11'b????1??????:
        \267  = b[27:24];
      11'b???1???????:
        \267  = b[31:28];
      11'b??1????????:
        \267  = b[35:32];
      11'b?1?????????:
        \267  = b[39:36];
      11'b1??????????:
        \267  = b[43:40];
      default:
        \267  = a;
    endcase
  endfunction
  assign _48_ = \267 (_18_, { _18_, _18_, ir_data_out[11:8], ir_data_out[11:8], _18_, ir_data_out[11:8], ir_data_out[11:8], _18_, _18_, _18_, _18_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [3:0] \268 ;
    input [3:0] a;
    input [43:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \268  = b[3:0];
      11'b?????????1?:
        \268  = b[7:4];
      11'b????????1??:
        \268  = b[11:8];
      11'b???????1???:
        \268  = b[15:12];
      11'b??????1????:
        \268  = b[19:16];
      11'b?????1?????:
        \268  = b[23:20];
      11'b????1??????:
        \268  = b[27:24];
      11'b???1???????:
        \268  = b[31:28];
      11'b??1????????:
        \268  = b[35:32];
      11'b?1?????????:
        \268  = b[39:36];
      11'b1??????????:
        \268  = b[43:40];
      default:
        \268  = a;
    endcase
  endfunction
  assign _49_ = \268 (_19_, { _19_, _19_, _19_, ir_data_out[7:4], _19_, ir_data_out[7:4], _19_, _19_, _19_, _19_, _19_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \274 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \274  = b[0:0];
      11'b?????????1?:
        \274  = b[1:1];
      11'b????????1??:
        \274  = b[2:2];
      11'b???????1???:
        \274  = b[3:3];
      11'b??????1????:
        \274  = b[4:4];
      11'b?????1?????:
        \274  = b[5:5];
      11'b????1??????:
        \274  = b[6:6];
      11'b???1???????:
        \274  = b[7:7];
      11'b??1????????:
        \274  = b[8:8];
      11'b?1?????????:
        \274  = b[9:9];
      11'b1??????????:
        \274  = b[10:10];
      default:
        \274  = a;
    endcase
  endfunction
  assign _50_ = \274 (_20_, { _20_, _20_, _20_, 3'h7, _20_, 1'h1, _20_, 1'h0, _20_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \280 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \280  = b[0:0];
      11'b?????????1?:
        \280  = b[1:1];
      11'b????????1??:
        \280  = b[2:2];
      11'b???????1???:
        \280  = b[3:3];
      11'b??????1????:
        \280  = b[4:4];
      11'b?????1?????:
        \280  = b[5:5];
      11'b????1??????:
        \280  = b[6:6];
      11'b???1???????:
        \280  = b[7:7];
      11'b??1????????:
        \280  = b[8:8];
      11'b?1?????????:
        \280  = b[9:9];
      11'b1??????????:
        \280  = b[10:10];
      default:
        \280  = a;
    endcase
  endfunction
  assign _51_ = \280 (_21_, { _21_, _21_, 2'h3, _21_, 2'h3, _21_, _21_, 1'h0, _21_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \284 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \284  = b[0:0];
      11'b?????????1?:
        \284  = b[1:1];
      11'b????????1??:
        \284  = b[2:2];
      11'b???????1???:
        \284  = b[3:3];
      11'b??????1????:
        \284  = b[4:4];
      11'b?????1?????:
        \284  = b[5:5];
      11'b????1??????:
        \284  = b[6:6];
      11'b???1???????:
        \284  = b[7:7];
      11'b??1????????:
        \284  = b[8:8];
      11'b?1?????????:
        \284  = b[9:9];
      11'b1??????????:
        \284  = b[10:10];
      default:
        \284  = a;
    endcase
  endfunction
  assign _52_ = \284 (_22_, { _22_, _22_, _22_, 1'h1, _22_, 1'h1, _22_, _22_, _22_, 1'h0, _22_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \287 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \287  = b[0:0];
      11'b?????????1?:
        \287  = b[1:1];
      11'b????????1??:
        \287  = b[2:2];
      11'b???????1???:
        \287  = b[3:3];
      11'b??????1????:
        \287  = b[4:4];
      11'b?????1?????:
        \287  = b[5:5];
      11'b????1??????:
        \287  = b[6:6];
      11'b???1???????:
        \287  = b[7:7];
      11'b??1????????:
        \287  = b[8:8];
      11'b?1?????????:
        \287  = b[9:9];
      11'b1??????????:
        \287  = b[10:10];
      default:
        \287  = a;
    endcase
  endfunction
  assign _53_ = \287 (_23_, { _23_, _23_, _23_, 1'h0, _23_, 1'h1, _23_, _23_, _23_, _23_, _23_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  function [0:0] \290 ;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \290  = b[0:0];
      11'b?????????1?:
        \290  = b[1:1];
      11'b????????1??:
        \290  = b[2:2];
      11'b???????1???:
        \290  = b[3:3];
      11'b??????1????:
        \290  = b[4:4];
      11'b?????1?????:
        \290  = b[5:5];
      11'b????1??????:
        \290  = b[6:6];
      11'b???1???????:
        \290  = b[7:7];
      11'b??1????????:
        \290  = b[8:8];
      11'b?1?????????:
        \290  = b[9:9];
      11'b1??????????:
        \290  = b[10:10];
      default:
        \290  = a;
    endcase
  endfunction
  assign _54_ = \290 (_24_, { _24_, _24_, _24_, 1'h1, _24_, 1'h0, _24_, _24_, _24_, _24_, _24_ }, { _35_, _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_, _26_, _25_ });
  assign _55_ = current_state == 4'h0;
  assign _56_ = current_state == 4'h1;
  assign _57_ = current_state == 4'h2;
  assign _58_ = ir_data_out[15:12] == 4'h0;
  assign _59_ = ir_data_out[15:12] == 4'h1;
  assign _60_ = ir_data_out[15:12] == 4'h2;
  assign _61_ = ir_data_out[15:12] == 4'h3;
  assign _62_ = ir_data_out[15:12] == 4'h4;
  assign _63_ = ir_data_out[15:12] == 4'h5;
  function [3:0] \340 ;
    input [3:0] a;
    input [23:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \340  = b[3:0];
      6'b????1?:
        \340  = b[7:4];
      6'b???1??:
        \340  = b[11:8];
      6'b??1???:
        \340  = b[15:12];
      6'b?1????:
        \340  = b[19:16];
      6'b1?????:
        \340  = b[23:20];
      default:
        \340  = a;
    endcase
  endfunction
  assign _64_ = \340 (4'h1, 24'h987654, { _63_, _62_, _61_, _60_, _59_, _58_ });
  assign _65_ = current_state == 4'h3;
  assign _66_ = rf_rp_zero ? 4'ha : 4'h1;
  assign _67_ = current_state == 4'h9;
  assign _68_ = current_state == 4'ha;
  function [3:0] \356 ;
    input [3:0] a;
    input [23:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \356  = b[3:0];
      6'b????1?:
        \356  = b[7:4];
      6'b???1??:
        \356  = b[11:8];
      6'b??1???:
        \356  = b[15:12];
      6'b?1????:
        \356  = b[19:16];
      6'b1?????:
        \356  = b[23:20];
      default:
        \356  = a;
    endcase
  endfunction
  assign _69_ = \356 (4'h1, { 4'h1, _66_, _64_, 12'h321 }, { _68_, _67_, _65_, _57_, _56_, _55_ });
  assign _70_ = reset ? 4'h0 : _69_;
  assign _71_ = current_state == 4'h0;
  assign _72_ = current_state == 4'h1;
  assign _73_ = current_state == 4'h2;
  assign _74_ = current_state == 4'h3;
  assign _75_ = current_state == 4'h4;
  assign _76_ = current_state == 4'h5;
  assign _77_ = current_state == 4'h6;
  assign _00_ = current_state == 4'h7;
  assign _01_ = current_state == 4'h8;
  assign _02_ = current_state == 4'h9;
  assign _03_ = current_state == 4'ha;
  function [3:0] \396 ;
    input [3:0] a;
    input [43:0] b;
    input [10:0] s;
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        \396  = b[3:0];
      11'b?????????1?:
        \396  = b[7:4];
      11'b????????1??:
        \396  = b[11:8];
      11'b???????1???:
        \396  = b[15:12];
      11'b??????1????:
        \396  = b[19:16];
      11'b?????1?????:
        \396  = b[23:20];
      11'b????1??????:
        \396  = b[27:24];
      11'b???1???????:
        \396  = b[31:28];
      11'b??1????????:
        \396  = b[35:32];
      11'b?1?????????:
        \396  = b[39:36];
      11'b1??????????:
        \396  = b[43:40];
      default:
        \396  = a;
    endcase
  endfunction
  assign _04_ = \396 (4'hf, 44'hba987654321, { _03_, _02_, _01_, _00_, _77_, _76_, _75_, _74_, _73_, _72_, _71_ });
  always @(posedge clock)
    _05_ <= next_state;
  always @(posedge clock)
    _06_ <= _36_;
  always @(posedge clock)
    _07_ <= _37_;
  always @(posedge clock)
    _08_ <= _38_;
  always @(posedge clock)
    _09_ <= _39_;
  always @(posedge clock)
    _10_ <= _40_;
  always @(posedge clock)
    _11_ <= _41_;
  always @(posedge clock)
    _12_ <= _42_;
  always @(posedge clock)
    _13_ <= _43_;
  always @(posedge clock)
    _14_ <= _44_;
  always @(posedge clock)
    _15_ <= _45_;
  always @(posedge clock)
    _16_ <= _46_;
  always @(posedge clock)
    _17_ <= _47_;
  always @(posedge clock)
    _18_ <= _48_;
  always @(posedge clock)
    _19_ <= _49_;
  always @(posedge clock)
    _20_ <= _50_;
  always @(posedge clock)
    _21_ <= _51_;
  always @(posedge clock)
    _22_ <= _52_;
  always @(posedge clock)
    _23_ <= _53_;
  always @(posedge clock)
    _24_ <= _54_;
  assign current_state = _05_;
  assign next_state = _70_;
  assign pc_clr = _06_;
  assign pc_ld = _07_;
  assign pc_inc = _08_;
  assign ir_ld = _09_;
  assign i_rd = _10_;
  assign leds = _04_;
  assign d_addr = _11_;
  assign d_rd = _12_;
  assign d_wr = _13_;
  assign rf_s1 = _14_;
  assign rf_s0 = _15_;
  assign rf_w_data = _16_;
  assign rf_w_addr = _17_;
  assign rf_rp_addr = _18_;
  assign rf_rq_addr = _19_;
  assign rf_w_wr = _20_;
  assign rf_rp_rd = _21_;
  assign rf_rq_rd = _22_;
  assign alu_s0 = _23_;
  assign alu_s1 = _24_;
endmodule

module ir(clock, ir_data_in, ir_ld, ir_data_out);
  wire [15:0] _0_;
  reg [15:0] _1_ = 16'hzzzz;
  input clock;
  wire clock;
  input [15:0] ir_data_in;
  wire [15:0] ir_data_in;
  output [15:0] ir_data_out;
  wire [15:0] ir_data_out;
  input ir_ld;
  wire ir_ld;
  assign _0_ = ir_ld ? ir_data_in : _1_;
  always @(posedge clock)
    _1_ <= _0_;
  assign ir_data_out = _1_;
endmodule

module muxf(s1, s0, ans, d_r_data, rf_w_data, w_data);
  wire _0_;
  wire _1_;
  wire _2_;
  wire [15:0] _3_;
  input [15:0] ans;
  wire [15:0] ans;
  input [15:0] d_r_data;
  wire [15:0] d_r_data;
  input [7:0] rf_w_data;
  wire [7:0] rf_w_data;
  input s0;
  wire s0;
  input s1;
  wire s1;
  wire [1:0] s1_s0;
  output [15:0] w_data;
  wire [15:0] w_data;
  assign _0_ = s1_s0 == 2'h0;
  assign _1_ = s1_s0 == 2'h1;
  assign _2_ = s1_s0 == 2'h2;
  function [15:0] \461 ;
    input [15:0] a;
    input [47:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \461  = b[15:0];
      3'b?1?:
        \461  = b[31:16];
      3'b1??:
        \461  = b[47:32];
      default:
        \461  = a;
    endcase
  endfunction
  assign _3_ = \461 (16'hzzzz, { 8'h00, rf_w_data, d_r_data, ans }, { _2_, _1_, _0_ });
  assign s1_s0 = { s1, s0 };
  assign w_data = _3_;
endmodule

module pc(clock, pc_inc, pc_clr, pc_ld, ir_inc, i_addr);
  wire [15:0] _0_;
  wire [15:0] _1_;
  wire [15:0] _2_;
  wire [15:0] _3_;
  wire [15:0] _4_;
  wire [15:0] _5_;
  reg [15:0] _6_ = 16'h0000;
  input clock;
  wire clock;
  output [15:0] i_addr;
  wire [15:0] i_addr;
  input [7:0] ir_inc;
  wire [7:0] ir_inc;
  input pc_clr;
  wire pc_clr;
  wire [15:0] pc_count;
  input pc_inc;
  wire pc_inc;
  input pc_ld;
  wire pc_ld;
  assign _0_ = pc_count + 16'h0001;
  assign _1_ = pc_count + { 8'h00, ir_inc };
  assign _2_ = _1_ - 16'h0001;
  assign _3_ = pc_ld ? _2_ : pc_count;
  assign _4_ = pc_clr ? 16'h0000 : _3_;
  assign _5_ = pc_inc ? _0_ : _4_;
  always @(posedge clock)
    _6_ <= _5_;
  assign pc_count = _6_;
  assign i_addr = pc_count;
endmodule

module po(rf_s0, rf_s1, rf_w_data, d_r_data, rf_w_wr, rf_rp_rd, rf_rq_rd, clock, rf_w_addr, rf_rp_addr, rf_rq_addr, alu_s0, alu_s1, rf_rp_zero, d_w_data);
  wire [15:0] _0_;
  wire [15:0] _1_;
  wire [15:0] _2_;
  wire _3_;
  wire [15:0] _4_;
  wire \alu_0:161 ;
  wire [15:0] \alu_0:162 ;
  input alu_s0;
  wire alu_s0;
  input alu_s1;
  wire alu_s1;
  wire [15:0] ans;
  input clock;
  wire clock;
  input [15:0] d_r_data;
  wire [15:0] d_r_data;
  output [15:0] d_w_data;
  wire [15:0] d_w_data;
  wire [15:0] \muxf_0:152 ;
  wire [15:0] \regf_0:155 ;
  wire [15:0] \regf_0:156 ;
  input [3:0] rf_rp_addr;
  wire [3:0] rf_rp_addr;
  input rf_rp_rd;
  wire rf_rp_rd;
  output rf_rp_zero;
  wire rf_rp_zero;
  input [3:0] rf_rq_addr;
  wire [3:0] rf_rq_addr;
  input rf_rq_rd;
  wire rf_rq_rd;
  input rf_s0;
  wire rf_s0;
  input rf_s1;
  wire rf_s1;
  input [3:0] rf_w_addr;
  wire [3:0] rf_w_addr;
  input [7:0] rf_w_data;
  wire [7:0] rf_w_data;
  input rf_w_wr;
  wire rf_w_wr;
  wire [15:0] rp_data;
  wire [15:0] rq_data;
  wire [15:0] w_data;
  alu alu_0 (
    .a(rp_data),
    .ans(_4_),
    .b(rq_data),
    .rp_zero(_3_),
    .s0(alu_s0),
    .s1(alu_s1)
  );
  muxf muxf_0 (
    .ans(ans),
    .d_r_data(d_r_data),
    .rf_w_data(rf_w_data),
    .s0(rf_s0),
    .s1(rf_s1),
    .w_data(_0_)
  );
  regf regf_0 (
    .clock(clock),
    .rp_addr(rf_rp_addr),
    .rp_data(_2_),
    .rp_rd(rf_rp_rd),
    .rq_addr(rf_rq_addr),
    .rq_data(_1_),
    .rq_rd(rf_rq_rd),
    .w_addr(rf_w_addr),
    .w_data(w_data),
    .w_wr(rf_w_wr)
  );
  assign ans = \alu_0:162 ;
  assign rp_data = \regf_0:156 ;
  assign rq_data = \regf_0:155 ;
  assign w_data = \muxf_0:152 ;
  assign \muxf_0:152  = _0_;
  assign \regf_0:155  = _1_;
  assign \regf_0:156  = _2_;
  assign \alu_0:161  = _3_;
  assign \alu_0:162  = _4_;
  assign rf_rp_zero = \alu_0:161 ;
  assign d_w_data = rp_data;
endmodule

module regf(w_addr, rp_addr, rq_addr, w_wr, rp_rd, rq_rd, clock, w_data, rq_data, rp_data);
  reg [15:0] _0_;
  reg [15:0] _1_;
  wire [335:0] _2_;
  wire [15:0] _3_;
  wire [335:0] _4_;
  wire [15:0] _5_;
  input clock;
  wire clock;
  input [3:0] rp_addr;
  wire [3:0] rp_addr;
  output [15:0] rp_data;
  wire [15:0] rp_data;
  input rp_rd;
  wire rp_rd;
  input [3:0] rq_addr;
  wire [3:0] rq_addr;
  output [15:0] rq_data;
  wire [15:0] rq_data;
  input rq_rd;
  wire rq_rd;
  input [3:0] w_addr;
  wire [3:0] w_addr;
  input [15:0] w_data;
  wire [15:0] w_data;
  input w_wr;
  wire w_wr;
  reg [15:0] rf [20:0];
  always @(posedge clock) begin
    if (w_wr)
      rf[{ 1'h0, w_addr }] <= w_data;
  end
  assign _5_ = rf[{ 1'h0, rq_addr }];
  assign _3_ = rf[{ 1'h0, rp_addr }];
  always @*
    if (rq_rd) _0_ = _5_;
  always @*
    if (rp_rd) _1_ = _3_;
  assign rq_data = _0_;
  assign rp_data = _1_;
endmodule

module uc(clock, reset, i_data, rf_rp_zero, leds, i_addr, i_rd, d_addr, d_rd, d_wr, rf_w_wr, rf_rp_rd, rf_rq_rd, rf_w_addr, rf_rp_addr, rf_rq_addr, rf_s0, rf_s1, rf_w_data, alu_s0, alu_s1
);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire [3:0] _05_;
  wire [7:0] _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [7:0] _11_;
  wire [3:0] _12_;
  wire [3:0] _13_;
  wire [3:0] _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire [15:0] _20_;
  wire [15:0] _21_;
  output alu_s0;
  wire alu_s0;
  output alu_s1;
  wire alu_s1;
  wire \bc_0:100 ;
  wire \bc_0:101 ;
  wire \bc_0:102 ;
  wire \bc_0:83 ;
  wire \bc_0:84 ;
  wire \bc_0:85 ;
  wire \bc_0:86 ;
  wire \bc_0:87 ;
  wire [3:0] \bc_0:88 ;
  wire [7:0] \bc_0:89 ;
  wire \bc_0:90 ;
  wire \bc_0:91 ;
  wire \bc_0:92 ;
  wire \bc_0:93 ;
  wire [7:0] \bc_0:94 ;
  wire [3:0] \bc_0:95 ;
  wire [3:0] \bc_0:96 ;
  wire [3:0] \bc_0:97 ;
  wire \bc_0:98 ;
  wire \bc_0:99 ;
  input clock;
  wire clock;
  output [7:0] d_addr;
  wire [7:0] d_addr;
  output d_rd;
  wire d_rd;
  output d_wr;
  wire d_wr;
  output [15:0] i_addr;
  wire [15:0] i_addr;
  input [15:0] i_data;
  wire [15:0] i_data;
  output i_rd;
  wire i_rd;
  wire [15:0] \ir_0:147 ;
  wire [15:0] ir_data_out;
  wire ir_ld;
  output [3:0] leds;
  wire [3:0] leds;
  wire [15:0] \pc_0:144 ;
  wire pc_clr;
  wire pc_inc;
  wire pc_ld;
  input reset;
  wire reset;
  output [3:0] rf_rp_addr;
  wire [3:0] rf_rp_addr;
  output rf_rp_rd;
  wire rf_rp_rd;
  input rf_rp_zero;
  wire rf_rp_zero;
  output [3:0] rf_rq_addr;
  wire [3:0] rf_rq_addr;
  output rf_rq_rd;
  wire rf_rq_rd;
  output rf_s0;
  wire rf_s0;
  output rf_s1;
  wire rf_s1;
  output [3:0] rf_w_addr;
  wire [3:0] rf_w_addr;
  output [7:0] rf_w_data;
  wire [7:0] rf_w_data;
  output rf_w_wr;
  wire rf_w_wr;
  bc bc_0 (
    .alu_s0(_18_),
    .alu_s1(_19_),
    .clock(clock),
    .d_addr(_06_),
    .d_rd(_07_),
    .d_wr(_08_),
    .i_rd(_04_),
    .ir_data_out(ir_data_out),
    .ir_ld(_03_),
    .leds(_05_),
    .pc_clr(_00_),
    .pc_inc(_02_),
    .pc_ld(_01_),
    .reset(reset),
    .rf_rp_addr(_13_),
    .rf_rp_rd(_16_),
    .rf_rp_zero(rf_rp_zero),
    .rf_rq_addr(_14_),
    .rf_rq_rd(_17_),
    .rf_s0(_10_),
    .rf_s1(_09_),
    .rf_w_addr(_12_),
    .rf_w_data(_11_),
    .rf_w_wr(_15_)
  );
  ir ir_0 (
    .clock(clock),
    .ir_data_in(i_data),
    .ir_data_out(_21_),
    .ir_ld(ir_ld)
  );
  pc pc_0 (
    .clock(clock),
    .i_addr(_20_),
    .ir_inc(ir_data_out[7:0]),
    .pc_clr(pc_clr),
    .pc_inc(pc_inc),
    .pc_ld(pc_ld)
  );
  assign pc_ld = \bc_0:84 ;
  assign pc_clr = \bc_0:83 ;
  assign pc_inc = \bc_0:85 ;
  assign ir_ld = \bc_0:86 ;
  assign ir_data_out = \ir_0:147 ;
  assign \bc_0:83  = _00_;
  assign \bc_0:84  = _01_;
  assign \bc_0:85  = _02_;
  assign \bc_0:86  = _03_;
  assign \bc_0:87  = _04_;
  assign \bc_0:88  = _05_;
  assign \bc_0:89  = _06_;
  assign \bc_0:90  = _07_;
  assign \bc_0:91  = _08_;
  assign \bc_0:92  = _09_;
  assign \bc_0:93  = _10_;
  assign \bc_0:94  = _11_;
  assign \bc_0:95  = _12_;
  assign \bc_0:96  = _13_;
  assign \bc_0:97  = _14_;
  assign \bc_0:98  = _15_;
  assign \bc_0:99  = _16_;
  assign \bc_0:100  = _17_;
  assign \bc_0:101  = _18_;
  assign \bc_0:102  = _19_;
  assign \pc_0:144  = _20_;
  assign \ir_0:147  = _21_;
  assign leds = \bc_0:88 ;
  assign i_addr = \pc_0:144 ;
  assign i_rd = \bc_0:87 ;
  assign d_addr = \bc_0:89 ;
  assign d_rd = \bc_0:90 ;
  assign d_wr = \bc_0:91 ;
  assign rf_w_wr = \bc_0:98 ;
  assign rf_rp_rd = \bc_0:99 ;
  assign rf_rq_rd = \bc_0:100 ;
  assign rf_w_addr = \bc_0:95 ;
  assign rf_rp_addr = \bc_0:96 ;
  assign rf_rq_addr = \bc_0:97 ;
  assign rf_s0 = \bc_0:93 ;
  assign rf_s1 = \bc_0:92 ;
  assign rf_w_data = \bc_0:94 ;
  assign alu_s0 = \bc_0:101 ;
  assign alu_s1 = \bc_0:102 ;
endmodule

module vahid6i(clock, reset, D_R_data, I_data, led_clock, leds, D_addr, D_rd, D_wr, D_W_data, I_rd, I_addr);
  wire [3:0] _00_;
  wire [3:0] _01_;
  wire [3:0] _02_;
  wire [3:0] _03_;
  wire _04_;
  wire _05_;
  wire [7:0] _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire [15:0] _10_;
  wire [15:0] _11_;
  wire _12_;
  wire [7:0] _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  input [15:0] D_R_data;
  wire [15:0] D_R_data;
  output [15:0] D_W_data;
  wire [15:0] D_W_data;
  output [7:0] D_addr;
  wire [7:0] D_addr;
  output D_rd;
  wire D_rd;
  output D_wr;
  wire D_wr;
  output [15:0] I_addr;
  wire [15:0] I_addr;
  input [15:0] I_data;
  wire [15:0] I_data;
  output I_rd;
  wire I_rd;
  wire alu_s0;
  wire alu_s1;
  input clock;
  wire clock;
  output led_clock;
  wire led_clock;
  output [3:0] leds;
  wire [3:0] leds;
  wire \po_0:59 ;
  wire [15:0] \po_0:60 ;
  input reset;
  wire reset;
  wire [3:0] rf_rp_addr;
  wire rf_rp_rd;
  wire rf_rp_zero;
  wire [3:0] rf_rq_addr;
  wire rf_rq_rd;
  wire rf_s0;
  wire rf_s1;
  wire [3:0] rf_w_addr;
  wire [7:0] rf_w_data;
  wire rf_w_wr;
  wire \uc_0:10 ;
  wire [7:0] \uc_0:11 ;
  wire \uc_0:12 ;
  wire \uc_0:13 ;
  wire \uc_0:14 ;
  wire \uc_0:15 ;
  wire \uc_0:16 ;
  wire [3:0] \uc_0:17 ;
  wire [3:0] \uc_0:18 ;
  wire [3:0] \uc_0:19 ;
  wire \uc_0:20 ;
  wire \uc_0:21 ;
  wire [7:0] \uc_0:22 ;
  wire \uc_0:23 ;
  wire \uc_0:24 ;
  wire [3:0] \uc_0:8 ;
  wire [15:0] \uc_0:9 ;
  po po_0 (
    .alu_s0(alu_s0),
    .alu_s1(alu_s1),
    .clock(clock),
    .d_r_data(D_R_data),
    .d_w_data(_10_),
    .rf_rp_addr(rf_rp_addr),
    .rf_rp_rd(rf_rp_rd),
    .rf_rp_zero(_09_),
    .rf_rq_addr(rf_rq_addr),
    .rf_rq_rd(rf_rq_rd),
    .rf_s0(rf_s0),
    .rf_s1(rf_s1),
    .rf_w_addr(rf_w_addr),
    .rf_w_data(rf_w_data),
    .rf_w_wr(rf_w_wr)
  );
  uc uc_0 (
    .alu_s0(_07_),
    .alu_s1(_08_),
    .clock(clock),
    .d_addr(_13_),
    .d_rd(_14_),
    .d_wr(_15_),
    .i_addr(_11_),
    .i_data(I_data),
    .i_rd(_12_),
    .leds(_00_),
    .reset(reset),
    .rf_rp_addr(_02_),
    .rf_rp_rd(_17_),
    .rf_rp_zero(rf_rp_zero),
    .rf_rq_addr(_03_),
    .rf_rq_rd(_18_),
    .rf_s0(_04_),
    .rf_s1(_05_),
    .rf_w_addr(_01_),
    .rf_w_data(_06_),
    .rf_w_wr(_16_)
  );
  assign rf_w_wr = \uc_0:14 ;
  assign rf_rp_rd = \uc_0:15 ;
  assign rf_rq_rd = \uc_0:16 ;
  assign rf_w_addr = \uc_0:17 ;
  assign rf_rp_addr = \uc_0:18 ;
  assign rf_rq_addr = \uc_0:19 ;
  assign rf_rp_zero = \po_0:59 ;
  assign rf_s0 = \uc_0:20 ;
  assign rf_s1 = \uc_0:21 ;
  assign rf_w_data = \uc_0:22 ;
  assign alu_s0 = \uc_0:23 ;
  assign alu_s1 = \uc_0:24 ;
  assign \uc_0:8  = _00_;
  assign \uc_0:9  = _11_;
  assign \uc_0:10  = _12_;
  assign \uc_0:11  = _13_;
  assign \uc_0:12  = _14_;
  assign \uc_0:13  = _15_;
  assign \uc_0:14  = _16_;
  assign \uc_0:15  = _17_;
  assign \uc_0:16  = _18_;
  assign \uc_0:17  = _01_;
  assign \uc_0:18  = _02_;
  assign \uc_0:19  = _03_;
  assign \uc_0:20  = _04_;
  assign \uc_0:21  = _05_;
  assign \uc_0:22  = _06_;
  assign \uc_0:23  = _07_;
  assign \uc_0:24  = _08_;
  assign \po_0:59  = _09_;
  assign \po_0:60  = _10_;
  assign led_clock = clock;
  assign leds = \uc_0:8 ;
  assign D_addr = \uc_0:11 ;
  assign D_rd = \uc_0:12 ;
  assign D_wr = \uc_0:13 ;
  assign D_W_data = \po_0:60 ;
  assign I_rd = \uc_0:10 ;
  assign I_addr = \uc_0:9 ;
endmodule
